### ISSUE TITLE
VitTracker crush 

### ISSUE THREAD

**Issue by saghavart** [opencv/opencv_zoo#261] opened 2024-06-12 09:45 UTC
Hi. I am encountering the problem when some number of pixels from video input are black. The error message is "error: (-4:Insufficient memory) Failed to allocate 39768204675(this number is variable) bytes in function 'OutOfMemoryError". I have tried to manually change the number of black pixels and depending on that the tracker crushes or works correctly. Error is occuring when calling model.infer()

**Comment by fengyuentau** [comment] 2024-06-12 09:52
Thanks for reporting this issue. May I know what is the input resolution in your case?
________________________________
发件人: Vardan ***@***.***>
发送时间: Wednesday, June 12, 2024 5:45:59 PM
收件人: opencv/opencv_zoo ***@***.***>
抄送: Subscribed ***@***.***>
主题: [opencv/opencv_zoo] VitTracker crush (Issue #261)


Hi. I am encountering the problem when some number of pixels from video input are black. The error message is "error: (-4:Insufficient memory) Failed to allocate 39768204675(this number is variable) bytes in function 'OutOfMemoryError". I have tried to manually change the number of black pixels and depending on that the tracker crushes or works correctly. Error is occuring when calling model.infer()

―

**Comment by saghavart** [comment] 2024-06-12 10:40
Thank you for quick response. It's (640,480). I've also tried with (1280,720)

**Comment by saghavart** [comment] 2024-06-12 10:42
To reproduce , you can set number of pixels to 0 manually like this 
```
frame[:,:,:] = 122
frame[:-padd, :-padd, :] = 0
```

**Comment by fengyuentau** [comment] 2024-06-12 12:44
Could you share the minimal reproducer?

**Comment by saghavart** [comment] 2024-06-12 13:03
Sure. Just insert following 3 lines in line 108 of demo.py file
```
padd = 70
frame[:,:,:]=122
frame[:-padd, :-padd, :] = 0
```

**Comment by fengyuentau** [comment] 2024-06-12 13:25
I tried with these three lines on my m1 macbook. Things are it did not crash but went very slow with your three lines of code. Also tried commented out `frame[:,:,:]=122`, it went smooth again. I guess some internal computation has problem with a massive area of pixel value 122.

**Comment by saghavart** [comment] 2024-06-12 13:43
Maybe this can help to reproduce. Remove those three lines, start camera, select an object and then close the camera with your hand or something black for 2-3 seconds. In my cases it writes target lost and then crushes

**Comment by fengyuentau** [comment] 2024-06-12 14:17
Okay, it can be reproduced on my side. Let me look into the issue tomorrow.

**Comment by fengyuentau** [comment] 2024-06-13 08:28
Okay, the problem is confirmed. Problem is when the target is lost, the bounding box gets larger and larger (the wrong bounding box pattern is recorded regardless of score) and the size of roi grows until out-of-memory error. See `crop_image` and `update`:

https://github.com/opencv/opencv/blob/a03b81316782ae30038b288fd3568993fa1e3538/modules/video/src/tracking/tracker_vit.cpp#L75-L93


https://github.com/opencv/opencv/blob/a03b81316782ae30038b288fd3568993fa1e3538/modules/video/src/tracking/tracker_vit.cpp#L199-L203

**Comment by fengyuentau** [comment] 2024-06-13 08:29
I will submit a PR to fix this problem.

**Comment by fengyuentau** [comment] 2024-06-17 12:39
@saghavart I submitted a PR to fix the problem hopefully. Feel free to review and test it https://github.com/opencv/opencv/issues/25760.

**Comment by fengyuentau** [comment] 2024-06-18 11:50
Hello @saghavart , my patch to fix the problem has been merged. Feel free to have a try on your side. Closing this issue for now.

**Closed by fengyuentau** 2024-06-18 11:50 UTC
Labels: bug
