### ISSUE TITLE
Open CV python not working with face detection model YuNet

### ISSUE THREAD

**Issue by stopslavery404** [opencv/opencv_zoo#170] opened 2023-06-09 10:38 UTC
This latest onnx model is not working with python library of open CV.
Getting errors related to shaape mismatch between layers.
Tried to view model on Neptune and tried with input size of 640,640
In this case the model works partially and shows another error.

**Comment by stopslavery404** [comment] 2023-06-09 10:39
I found the March 2022 onnx model from somewhere and that model is working fine with cc2.
But unable to use 2023 model

**Comment by stopslavery404** [comment] 2023-06-09 10:40
I found the March 2022 onnx model from somewhere and that model is working fine with cc2.
But unable to use 2023 model

**Comment by fengyuentau** [comment] 2023-06-10 12:43
Hello! I think you are talking about the face detection model `YuNet`, right?

If so, the model was upgraded to match the upcoming OpenCV 4.8.0 release. The new one (2023) is not compatible with the old API. So you will have to build the latest OpenCV yourself to use the new one.

Also you can do a checkout to get the old model:

```
git checkout 7e062e54cf5410c09b795ff71b4a255e58498c79
```

This issue is a duplicate of https://github.com/opencv/opencv_zoo/issues/172.

**Closed** 2023-06-17 11:46 UTC
Labels: question

**Comment by fzarief** [comment] 2023-06-19 09:20
> I found the March 2022 onnx model from somewhere and that model is working fine with cc2. But unable to use 2023 model

Can you share the  March 2022 onnx model please?

**Comment by fengyuentau** [comment] 2023-06-24 04:27
@fzarief visit https://github.com/opencv/opencv_zoo/tree/7e062e54cf5410c09b795ff71b4a255e58498c79/models/face_detection_yunet, click the model and click download.
