### ISSUE TITLE
the question of face_recognition_sface_2021dec_int8 for java

### ISSUE THREAD

**Issue by 12341234-yangboran** [opencv/opencv_zoo#187] opened 2023-06-27 07:26 UTC
<img width="354" alt="ab08f10f81da851ecfa2be6cd795d2d" src="https://github.com/opencv/opencv_zoo/assets/74187378/bddb8163-8631-499b-bebb-ed0d370182f0">

**Comment by 12341234-yangboran** [comment] 2023-06-27 07:27
`FaceRecognizerSF faceRecognizerSF = FaceRecognizerSF.create("C:/Users/y1793/Downloads/face_recognition_sface_2021dec.onnx", "");
        Mat alignFaceA = new Mat();
        faceRecognizerSF.alignCrop(imageA, faceA, alignFaceA);
        Mat alignFaceB = new Mat();
        faceRecognizerSF.alignCrop(imageB, faceB, alignFaceB);

        
        Mat featureA = new Mat();
        faceRecognizerSF.feature(alignFaceA, featureA);
        Mat featureB = new Mat();
        faceRecognizerSF.feature(alignFaceB, featureB);`

**Comment by 12341234-yangboran** [comment] 2023-06-27 07:33
`faceRecognizerSF.alignCrop(imageA, faceA.row(0), alignFaceA);`
like this?

**Comment by fengyuentau** [comment] 2023-06-27 07:41
See Python demo:

https://github.com/opencv/opencv_zoo/blob/f872270fbb034ac326ee5a8d6343299bde765bc4/models/face_recognition_sface/demo.py#L80

https://github.com/opencv/opencv_zoo/blob/f872270fbb034ac326ee5a8d6343299bde765bc4/models/face_recognition_sface/sface.py#L54-L63

A face box should be sent to `alignCrop`. The face box should have the format as follows:

```
[x1, y1, w, h, lm1_x, lm1_y, ..., lm5_x, lm5_y]
```

, where `x1, y1` are the top-left corner point and `lm1, lm2, lm3, lm4, lm5` are right eye, left eye, nose tip, right corner of mouth, left corner of mouth respectively. See https://github.com/opencv/opencv_zoo/tree/main/models/face_detection_yunet for more details.

**Comment by 12341234-yangboran** [comment] 2023-06-30 09:14
face_recognition_sface_2021dec_int8.onnx may be have something wrong.
![63193f35936cfb5897eb8d24ea100433](https://github.com/opencv/opencv_zoo/assets/74187378/fadf83c8-c9ee-4a6f-89e5-fd564644aa28)
![2a453f25ef95ec02e4ea8c21bdd2b237](https://github.com/opencv/opencv_zoo/assets/74187378/a2ff38a3-7a6d-4e82-a685-9e26f1eee9fe)
there are my image
faceRecognizerSF.match return 0.99999

**Comment by 12341234-yangboran** [comment] 2023-06-30 09:17
`FaceDetectorYN faceDetectorYN = FaceDetectorYN.create("C:/Users/y1793/Downloads/face_detection_yunet_2022mar_int8.onnx", "", new Size(), score_thresh, nms_thresh, top_k);`
`FaceRecognizerSF faceRecognizerSF = FaceRecognizerSF.create("C:/Users/y1793/Downloads/face_recognition_sface_2021dec_int8.onnx", "");`

**Comment by rh-id** [comment] 2023-07-11 13:50
hi @fengyuentau 

+1 for this, i think something is wrong with the model scoring. i tested 2 faces that are very different, yet the score indicates it was identical.

my code:
https://github.com/rh-id/a-jarwis/blob/master/ml-engine/src/androidTest/java/m/co/rh/id/a_jarwis/ml_engine/provider/component/FaceEngineTest.java#L77-L92

  https://github.com/rh-id/a-jarwis/blob/master/ml-engine/src/main/java/m/co/rh/id/a_jarwis/ml_engine/provider/component/FaceEngine.java#L61-L79


https://github.com/rh-id/a-jarwis/blob/master/ml-engine/src/main/java/m/co/rh/id/a_jarwis/ml_engine/provider/component/FaceEngine.java#L139-L164

**Comment by fengyuentau** [comment] 2023-07-12 09:28
> hi @fengyuentau
> 
> +1 for this, i think something is wrong with the model scoring. i tested 2 faces that are very different, yet the score indicates it was identical.
> 
> my code: https://github.com/rh-id/a-jarwis/blob/master/ml-engine/src/androidTest/java/m/co/rh/id/a_jarwis/ml_engine/provider/component/FaceEngineTest.java#L77-L92
> 
> https://github.com/rh-id/a-jarwis/blob/master/ml-engine/src/main/java/m/co/rh/id/a_jarwis/ml_engine/provider/component/FaceEngine.java#L61-L79
> 
> https://github.com/rh-id/a-jarwis/blob/master/ml-engine/src/main/java/m/co/rh/id/a_jarwis/ml_engine/provider/component/FaceEngine.java#L139-L164

1. Draw the detected face bounding boxes on the image to see whether faces are detected correctly.
2. Make sure you send the correct face bounding box along with its matching image to the API.
3. Could you test your image with the Python demo here? If the results are still wrong, then this model does not satisfy your need.

**Comment by rh-id** [comment] 2023-07-12 12:24
hi @fengyuentau , I think the `demo.py` result is correct only my code is incorrect, you could ignore my questions. thanks and sorry for the trouble

**Comment by 12341234-yangboran** [comment] 2023-07-21 02:04
> hi @fengyuentau , I think the `demo.py` result is correct only my code is incorrect, you could ignore my questions. thanks and sorry for the trouble

You need clone the result of face recogniz feature  to a new entity。

**Comment by 12341234-yangboran** [comment] 2023-07-21 02:08
> hi @fengyuentau , I think the `demo.py` result is correct only my code is incorrect, you could ignore my questions. thanks and sorry for the trouble

like this
        Mat featureA = new Mat();
        faceRecognizer.feature(alignFaceA, featureA);
        featureA = featureA.clone();
        Mat featureB = new Mat();
        faceRecognizer.feature(alignFaceB, featureB);
        featureB = featureB.clone();

**Comment by rh-id** [comment] 2023-07-22 00:12
hi @12341234-yangboran 

Yes that is right, it works. I think you could close this issue since it seemed the issue is solved.

**Closed** 2023-07-22 14:59 UTC
Labels: question
