### ISSUE TITLE
SFaceRecognizer model face recognition C++ test failed

### ISSUE THREAD

**Issue by Linktin** [opencv/opencv_zoo#256] opened 2024-05-08 16:17 UTC
YuNet model("/home/hy/code/face_detection_yunet_2023mar.onnx", cv::Size(160, 120), 0.9, 0.3, 5000, 0, 0);
    SFace sface("/home/hy/code/face_recognition_sface_2021dec_int8.onnx",0,0,0);
    DetectedFace dface1,dface2;

    Mat img1 = imread("/home/hy/code/heye.jpg");
    Mat img2 = imread("/home/hy/code/demo.jpg");

    //face detection
    model.setInputSize(Size(img1.cols,img1.rows));
    dface1 = model.infer(img1);
    model.setInputSize(Size(img2.cols,img2.rows));
    dface2 = model.infer(img2);

    std::cout<<"face1 nums:"<<dface1.nums<<std::endl;
    std::cout<<"face2 nums:"<<dface2.nums<<std::endl;
    //face recognition
    auto tick_meter = cv::TickMeter();
    tick_meter.start();
   // std::cout<<"scores:"<<static_cast<double>(dface1.faces.at<float>(0, 14))<<std::endl;
    cv::Range cols_range(0, 13);
    cv::Mat face1_features = dface1.faces.row(0).colRange(cols_range);
    cv::Mat face2_features = dface2.faces.row(0).colRange(cols_range);

    pair<double, bool> res = sface.match(img1, face1_features, img2, face2_features);

When I use the image and the detected facial feature information using YuNet for inference with this model, the result is as follows:
![image](https://github.com/opencv/opencv_zoo/assets/103801980/cb23641c-11d4-42e8-b304-7298e69de6bb)
In any case, the facial matching score is always 1! This is not normal.

**Comment by Linktin** [comment] 2024-05-09 06:57
已解决，feature的浅拷贝导致得到相同的人脸特征，加上clone()函数进行深拷贝即可解决。
     Mat feature1 = infer(image1,face1).clone(); // 提取第一张图像的特征
     Mat feature2 = infer(image2,face2).clone(); // 提取第二张图像的特征

**Comment by fengyuentau** [comment] 2024-05-14 02:02
Duplicate of https://github.com/opencv/opencv_zoo/issues/189

**Closed by fengyuentau** 2024-05-14 02:02 UTC
