### ISSUE TITLE
pose_estimation_mediapipe may be have something wrong

### ISSUE THREAD

**Issue by xiaopengaia** [opencv/opencv_zoo#188] opened 2023-06-30 06:04 UTC
demo from pose_estimation_mediapipe may be have something wrong.

Same input into but get  different output

This difference comes from the pre-processing

**Comment by fengyuentau** [comment] 2023-06-30 06:36
Please provide step-by-step reproducer along with input image.

**Comment by xiaopengaia** [comment] 2023-06-30 06:46
> Please provide step-by-step reproducer along with input image.

thank you for response！

`python demo.py --input yogo.jpg`

the yogo.jpg from 

[]( https://cn.bing.com/images/search?view=detailV2&ccid=zFGhM1jZ&id=93FA45311778DBD7F09D437A8FF093EC31914A9A&thid=OIP.zFGhM1jZLGgQii0GNqv5xgHaEt&mediaurl=https%3a%2f%2fts1.cn.mm.bing.net%2fth%2fid%2fR-C.cc51a13358d92c68108a2d0636abf9c6%3frik%3dmkqRMeyT8I96Qw%26riu%3dhttp%253a%252f%252fa1.att.hudong.com%252f18%252f85%252f19300001266041131399853057747.jpg%26ehk%3dlBODODi3zpeah%252fcwNoL3fVJ3el67g5rUsee3epCMZGU%253d%26risl%3d%26pid%3dImgRaw%26r%3d0&exph=2177&expw=3417&q=%e7%91%9c%e4%bc%bd%e5%9b%be%e7%89%87&simid=608043464134119488&FORM=IRPRST&ck=F544B32086462946E6C3EB2ABC42775C&selectedIndex=8&ajaxhist=0&ajaxserp=0)

**Comment by WanliZhong** [comment] 2023-06-30 07:09
@xiaopengaia Hi, thanks for your report. I think why this happen is the OpenCV 4.7.0 has something wrong I have ever met. But it's already been fixed in OpenCV Dev version, so you can build a dev version of OpenCV or wait some days for 4.8.0 released (It's coming soon!). Also you can use `pip uninstall opencv-python` and `pip install opencv-python-rolling==4.7.0.*`

**Comment by xiaopengaia** [comment] 2023-06-30 07:29
Awsome!  It can work now. 

there is no problem with the pre-processing, I made a mistake.  

the difference comes from onnx reasoning.

Best Wish！

**Comment by fengyuentau** [comment] 2023-06-30 07:49
> I will modify the minimal OpenCV version of this model.

Minimal OpenCV version should be updated for all models once opencv-python 4.8 is released.

**Comment by WanliZhong** [comment] 2023-06-30 14:19
@xiaopengaia Hi, `opencv-python` has been released! You can update your OpenCV version by `pip install -U opencv-python` and this bug should be solved.

**Comment by xiaopengaia** [comment] 2023-07-01 07:01
Thank you very much ! @WanliZhong

**Closed** 2023-07-01 09:36 UTC
Labels: bug

**Comment by LaurentBerger** [comment] 2023-07-01 10:19
I followed the issue and I need your confirm result using demo.py with this image (image given here but resize to 20%)
Original image
![R20pc](https://github.com/opencv/opencv_zoo/assets/3591626/26b5c58c-e070-4383-9c3c-45ef5a8a7017)

results
![image](https://github.com/opencv/opencv_zoo/assets/3591626/ec923b6f-1eea-403d-9591-54b75f878340)

![image](https://github.com/opencv/opencv_zoo/assets/3591626/9e951de0-3b79-4113-974e-46188fa59ed1)

**Comment by LaurentBerger** [comment] 2023-07-03 07:13
Problem exist because there is an image rotation (60 degrees). When image is rotated hands are lost.

**Comment by LaurentBerger** [comment] 2023-07-03 09:03
That's not clear for me why image need to be rotated

**Comment by WanliZhong** [comment] 2023-07-03 09:23
you can look at [model card](https://drive.google.com/file/d/10WlcTvrQnR_R2TdTmKw0nkyRLqrwNkWU/preview?pli=1) and it's defined in the input of this model.

![image](https://github.com/opencv/opencv_zoo/assets/49567307/63b6da0a-0545-410f-8ba1-e9841e13ccb4)
